openapi: 3.0.3
info:
  title: Stock Indicator Analysis Open API
  description: |-
    Stock Indicator Analysis API is used to get various stock indicator results based on the test required to be performed
    The API is to be consumed by the frontend team to display the charts required for the stock analysis and indicators
  version: 0.0.1
servers:
  - url: http://3.84.200.180/
security:
  - ApiKeyAuth: []
tags:
  - name: GeneralStockInfo
    description: Provide Candle stick data and general stock information
  - name: Overlays
    description:
      Technical indicators that use the same scale as prices are plotted
      over the top of the prices on a stock chart.
  - name: Oscillators
    description:
      Technical indicators that oscillate between a local minimum and maximum
      are plotted above or below a price chart.
paths:
  /candlesticknew:
    get:
      tags:
        - GeneralStockInfo
      summary: The average price over the specified period
      operationId: calculate_candlestick_updated
      parameters:
        - name: symbol
          in: query
          description: Ticker Symbol Required
          required: true
          style: form
          explode: true
          schema:
            type: string
        - name: period
          in: query
          description: The Analysis Period required
          required: true
          style: form
          explode: true
          schema:
            type: string
            enum:
              - day
              - hour
              - week
              - month
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/candlestick"
        "401":
          description: API key is missing or invalid
        "404":
          description: The specified symbol was not found
        "405":
          description: Validation exception
      x-openapi-router-controller: swagger_server.controllers.general_stock_info_controller
  /adl:
    get:
      tags:
        - Overlays
      summary:
        Accumulation/Distribution indicator utilizes the relative position
        of the close to it's High-Low range with volume.  Then it is cumulated.
      operationId: calculate_adl
      parameters:
        - name: symbol
          in: query
          description: Ticker Symbol Required
          required: true
          style: form
          explode: true
          schema:
            type: string
        - name: period
          in: query
          description: The Analysis Period required
          required: true
          style: form
          explode: true
          schema:
            type: string
            enum:
              - day
              - hour
              - week
              - month
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/adl"
        "401":
          description: API key is missing or invalid
        "404":
          description: The specified symbol was not found
        "405":
          description: Validation exception
      x-openapi-router-controller: swagger_server.controllers.overlays_controller
  /sma:
    get:
      tags:
        - Overlays
      summary: The average price over the specified period
      operationId: calculate_sma
      parameters:
        - name: symbol
          in: query
          description: Ticker Symbol Required
          required: true
          style: form
          explode: true
          schema:
            type: string
        - name: period
          in: query
          description: The Analysis Period required
          required: true
          style: form
          explode: true
          schema:
            type: string
            enum:
              - day
              - hour
              - week
              - month
        - name: length
          in: query
          description: The short period
          required: false
          style: form
          explode: true
          schema:
            type: integer
            default: 5
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/sma"
        "401":
          description: API key is missing or invalid
        "404":
          description: The specified symbol was not found
        "405":
          description: Validation exception
      x-openapi-router-controller: swagger_server.controllers.overlays_controller
  /ema:
    get:
      tags:
        - Overlays
      summary: The average price over the specified period
      operationId: calculate_ema
      parameters:
        - name: symbol
          in: query
          description: Ticker Symbol Required
          required: true
          style: form
          explode: true
          schema:
            type: string
        - name: period
          in: query
          description: The Analysis Period required
          required: true
          style: form
          explode: true
          schema:
            type: string
            enum:
              - day
              - hour
              - week
              - month
        - name: length
          in: query
          description: The short period
          required: false
          style: form
          explode: true
          schema:
            type: integer
            default: 5
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ema"
        "401":
          description: API key is missing or invalid
        "404":
          description: The specified symbol was not found
        "405":
          description: Validation exception
      x-openapi-router-controller: swagger_server.controllers.overlays_controller
  /bollingernew:
    get:
      tags:
        - Overlays
      summary:
        An oscillator meaning that it operates between or within a set range
        of numbers or parameters..
      operationId: calculate_bollinger_bands_updated
      parameters:
        - name: symbol
          in: query
          description: Ticker Symbol Required
          required: true
          style: form
          explode: true
          schema:
            type: string
        - name: period
          in: query
          description: The Analysis Period required
          required: true
          style: form
          explode: true
          schema:
            type: string
            enum:
              - day
              - hour
              - week
              - month
        - name: length
          in: query
          description: The short period
          required: false
          style: form
          explode: true
          schema:
            type: integer
            default: 5
        - name: standard_deviation
          in: query
          description: The long period
          required: false
          style: form
          explode: true
          schema:
            type: integer
            default: 2
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/bollingernew"
        "401":
          description: API key is missing or invalid
        "404":
          description: The specified symbol was not found
        "405":
          description: Validation exception
      x-openapi-router-controller: swagger_server.controllers.overlays_controller
  /adx:
    get:
      tags:
        - Overlays
      summary:
        Average Directional Movement is meant to quantify trend strength by
        measuring the amount of movement in a single direction.
      operationId: calculate_adx
      parameters:
        - name: symbol
          in: query
          description: Ticker Symbol Required
          required: true
          style: form
          explode: true
          schema:
            type: string
        - name: period
          in: query
          description: The Analysis Period required
          required: true
          style: form
          explode: true
          schema:
            type: string
            enum:
              - day
              - hour
              - week
              - month
        - name: length
          in: query
          description: period length
          required: false
          style: form
          explode: true
          schema:
            type: number
            default: 14
        - name: scalar
          in: query
          description: How much to magnify
          required: false
          style: form
          explode: true
          schema:
            type: number
            default: 100
        - name: drift
          in: query
          description: diff period
          required: false
          style: form
          explode: true
          schema:
            type: number
            default: 1
        - name: lensig
          in: query
          description: Signal Length
          required: false
          style: form
          explode: true
          schema:
            type: number
            default: 14
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/adx"
        "401":
          description: API key is missing or invalid
        "404":
          description: The specified symbol was not found
        "405":
          description: Validation exception
      x-openapi-router-controller: swagger_server.controllers.overlays_controller
  /macd:
    get:
      tags:
        - Oscillators
      summary:
        "The MACD is a popular indicator to that is used to identify a security's\
        \ trend. While APO and MACD are the same calculation, MACD also returns two\
        \ more series called Signal and Histogram. The Signal is an EMA of MACD and\
        \ the Histogram is the difference of MACD and Signal."
      operationId: calculate_macd
      parameters:
        - name: symbol
          in: query
          description: Ticker Symbol Required
          required: true
          style: form
          explode: true
          schema:
            type: string
        - name: period
          in: query
          description: The Analysis Period required
          required: true
          style: form
          explode: true
          schema:
            type: string
            enum:
              - day
              - hour
              - week
              - month
        - name: fast
          in: query
          description: The short period
          required: false
          style: form
          explode: true
          schema:
            type: number
            default: 12
        - name: slow
          in: query
          description: The long period
          required: false
          style: form
          explode: true
          schema:
            type: number
            default: 26
        - name: signal
          in: query
          description: The signal period
          required: false
          style: form
          explode: true
          schema:
            type: number
            default: 9
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/macd"
        "401":
          description: API key is missing or invalid
        "404":
          description: The specified symbol was not found
        "405":
          description: Validation exception
      x-openapi-router-controller: swagger_server.controllers.oscillators_controller
  /ppo:
    get:
      tags:
        - Oscillators
      summary: The Percentage Price Oscillator is similar to MACD in measuring momentum.
      operationId: calculate_ppo
      parameters:
        - name: symbol
          in: query
          description: Ticker Symbol Required
          required: true
          style: form
          explode: true
          schema:
            type: string
        - name: period
          in: query
          description: The Analysis Period required
          required: true
          style: form
          explode: true
          schema:
            type: string
            enum:
              - day
              - hour
              - week
              - month
        - name: fast
          in: query
          description: The short period
          required: false
          style: form
          explode: true
          schema:
            type: number
            default: 12
        - name: slow
          in: query
          description: The long period
          required: false
          style: form
          explode: true
          schema:
            type: number
            default: 26
        - name: signal
          in: query
          description: The signal period
          required: false
          style: form
          explode: true
          schema:
            type: number
            default: 9
        - name: scalar
          in: query
          description: How much to magnify
          required: false
          style: form
          explode: true
          schema:
            type: number
            default: 100
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ppo"
        "401":
          description: API key is missing or invalid
        "404":
          description: The specified symbol was not found
        "405":
          description: Validation exception
      x-openapi-router-controller: swagger_server.controllers.oscillators_controller
  /pvo:
    get:
      tags:
        - Oscillators
      summary: Percentage Volume Oscillator is a Momentum Oscillator for Volume.
      operationId: calculate_pvo
      parameters:
        - name: symbol
          in: query
          description: Ticker Symbol Required
          required: true
          style: form
          explode: true
          schema:
            type: string
        - name: period
          in: query
          description: The Analysis Period required
          required: true
          style: form
          explode: true
          schema:
            type: string
            enum:
              - day
              - hour
              - week
              - month
        - name: fast
          in: query
          description: The short period
          required: false
          style: form
          explode: true
          schema:
            type: number
            default: 12
        - name: slow
          in: query
          description: The long period
          required: false
          style: form
          explode: true
          schema:
            type: number
            default: 26
        - name: signal
          in: query
          description: The signal period
          required: false
          style: form
          explode: true
          schema:
            type: number
            default: 9
        - name: scalar
          in: query
          description: How much to magnify
          required: false
          style: form
          explode: true
          schema:
            type: number
            default: 100
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/pvo"
        "401":
          description: API key is missing or invalid
        "404":
          description: The specified symbol was not found
        "405":
          description: Validation exception
      x-openapi-router-controller: swagger_server.controllers.oscillators_controller
  /psar:
    get:
      tags:
        - Oscillators
      summary:
        An oscillator meaning that it operates between or within a set range
        of numbers or parameters..
      operationId: calculate_psar
      parameters:
        - name: symbol
          in: query
          description: Ticker Symbol Required
          required: true
          style: form
          explode: true
          schema:
            type: string
        - name: period
          in: query
          description: The Analysis Period required
          required: true
          style: form
          explode: true
          schema:
            type: string
            enum:
              - day
              - hour
              - week
              - month
        - name: initial_acceleration
          in: query
          description: The psar initial acceleration
          required: false
          style: form
          explode: true
          schema:
            type: number
            default: 0.02
        - name: acceleration
          in: query
          description: The psar acceleration
          required: false
          style: form
          explode: true
          schema:
            type: number
            default: 0.02
        - name: max_acceleration
          in: query
          description: The psar max acceleration
          required: false
          style: form
          explode: true
          schema:
            type: number
            default: 0.2
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/psar"
        "401":
          description: API key is missing or invalid
        "404":
          description: The specified symbol was not found
        "405":
          description: Validation exception
      x-openapi-router-controller: swagger_server.controllers.oscillators_controller
  /cci:
    get:
      tags:
        - Oscillators
      summary:
        Used to help determine when an investment vehicle is reaching a condition
        of being overbought or oversold.
      operationId: calculate_cci
      parameters:
        - name: symbol
          in: query
          description: Ticker Symbol Required
          required: true
          style: form
          explode: true
          schema:
            type: string
        - name: period
          in: query
          description: The Analysis Period required
          required: true
          style: form
          explode: true
          schema:
            type: string
            enum:
              - day
              - hour
              - week
              - month
        - name: length
          in: query
          description: period length
          required: false
          style: form
          explode: true
          schema:
            type: number
            default: 14
        - name: cci_scaling_constant
          in: query
          description: scaling constant
          required: false
          style: form
          explode: true
          schema:
            type: number
            default: 0.015
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/cci"
        "401":
          description: API key is missing or invalid
        "404":
          description: The specified symbol was not found
        "405":
          description: Validation exception
      x-openapi-router-controller: swagger_server.controllers.oscillators_controller
  /mfi:
    get:
      tags:
        - Oscillators
      summary:
        The Money Flow Index (MFI) is an oscillator that uses both price and
        volume to measure buying and selling pressure over a specified period of time.
      operationId: calculate_mfi
      parameters:
        - name: symbol
          in: query
          description: Ticker Symbol Required
          required: true
          style: form
          explode: true
          schema:
            type: string
        - name: period
          in: query
          description: The Analysis Period required
          required: true
          style: form
          explode: true
          schema:
            type: string
            enum:
              - day
              - hour
              - week
              - month
        - name: length
          in: query
          description: period length
          required: false
          style: form
          explode: true
          schema:
            type: number
            default: 14
        - name: drift
          in: query
          description: diff period
          required: false
          style: form
          explode: true
          schema:
            type: number
            default: 1
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/mfi"
        "401":
          description: API key is missing or invalid
        "404":
          description: The specified symbol was not found
        "405":
          description: Validation exception
      x-openapi-router-controller: swagger_server.controllers.oscillators_controller
  /obv:
    get:
      tags:
        - Oscillators
      summary:
        The Money Flow Index (MFI) is an oscillator that uses both price and
        volume to measure buying and selling pressure over a specified period of time.
      operationId: calculate_obv
      parameters:
        - name: symbol
          in: query
          description: Ticker Symbol Required
          required: true
          style: form
          explode: true
          schema:
            type: string
        - name: period
          in: query
          description: The Analysis Period required
          required: true
          style: form
          explode: true
          schema:
            type: string
            enum:
              - day
              - hour
              - week
              - month
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/obv"
        "401":
          description: API key is missing or invalid
        "404":
          description: The specified symbol was not found
        "405":
          description: Validation exception
      x-openapi-router-controller: swagger_server.controllers.oscillators_controller
  /roc:
    get:
      tags:
        - Oscillators
      summary:
        Elder's Force Index measures the power behind a price movement using
        price and volume as well as potential reversals and price corrections.
      operationId: calculate_roc
      parameters:
        - name: symbol
          in: query
          description: Ticker Symbol Required
          required: true
          style: form
          explode: true
          schema:
            type: string
        - name: period
          in: query
          description: The Analysis Period required
          required: true
          style: form
          explode: true
          schema:
            type: string
            enum:
              - day
              - hour
              - week
              - month
        - name: length
          in: query
          description: period length
          required: false
          style: form
          explode: true
          schema:
            type: number
            default: 1
        - name: scalar
          in: query
          description: How much to magnify
          required: false
          style: form
          explode: true
          schema:
            type: number
            default: 100
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/roc"
        "401":
          description: API key is missing or invalid
        "404":
          description: The specified symbol was not found
        "405":
          description: Validation exception
      x-openapi-router-controller: swagger_server.controllers.oscillators_controller
  /efi:
    get:
      tags:
        - Oscillators
      summary:
        Elder's Force Index measures the power behind a price movement using
        price and volume as well as potential reversals and price corrections.
      operationId: calculate_efi
      parameters:
        - name: symbol
          in: query
          description: Ticker Symbol Required
          required: true
          style: form
          explode: true
          schema:
            type: string
        - name: period
          in: query
          description: The Analysis Period required
          required: true
          style: form
          explode: true
          schema:
            type: string
            enum:
              - day
              - hour
              - week
              - month
        - name: length
          in: query
          description: period length
          required: false
          style: form
          explode: true
          schema:
            type: number
            default: 13
        - name: drift
          in: query
          description: diff period
          required: false
          style: form
          explode: true
          schema:
            type: number
            default: 1
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/efi"
        "401":
          description: API key is missing or invalid
        "404":
          description: The specified symbol was not found
        "405":
          description: Validation exception
      x-openapi-router-controller: swagger_server.controllers.oscillators_controller
  /cmf:
    get:
      tags:
        - Oscillators
      summary:
        Chailin Money Flow measures the amount of money flow volume over a
        specific period in conjunction with Accumulation/Distribution.
      operationId: calculate_cmf
      parameters:
        - name: symbol
          in: query
          description: Ticker Symbol Required
          required: true
          style: form
          explode: true
          schema:
            type: string
        - name: period
          in: query
          description: The Analysis Period required
          required: true
          style: form
          explode: true
          schema:
            type: string
            enum:
              - day
              - hour
              - week
              - month
        - name: length
          in: query
          description: period length
          required: false
          style: form
          explode: true
          schema:
            type: number
            default: 20
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/cmf"
        "401":
          description: API key is missing or invalid
        "404":
          description: The specified symbol was not found
        "405":
          description: Validation exception
      x-openapi-router-controller: swagger_server.controllers.oscillators_controller
  /rsi:
    get:
      tags:
        - Oscillators
      summary:
        The Relative Strength Index is popular momentum oscillator used to
        measure the velocity as well as the magnitude of directional price movements.
      operationId: calculate_rsi
      parameters:
        - name: symbol
          in: query
          description: Ticker Symbol Required
          required: true
          style: form
          explode: true
          schema:
            type: string
        - name: period
          in: query
          description: The Analysis Period required
          required: true
          style: form
          explode: true
          schema:
            type: string
            enum:
              - day
              - hour
              - week
              - month
        - name: length
          in: query
          description: period length
          required: false
          style: form
          explode: true
          schema:
            type: number
            default: 14
        - name: scalar
          in: query
          description: How much to magnify
          required: false
          style: form
          explode: true
          schema:
            type: number
            default: 100
        - name: drift
          in: query
          description: The difference period
          required: false
          style: form
          explode: true
          schema:
            type: number
            default: 1
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/rsi"
        "401":
          description: API key is missing or invalid
        "404":
          description: The specified symbol was not found
        "405":
          description: Validation exception
      x-openapi-router-controller: swagger_server.controllers.oscillators_controller
  /stoch:
    get:
      tags:
        - Oscillators
      summary:
        The Stochastic Oscillator (STOCH) was developed by George Lane in the
        1950's. He believed this indicator was a good way to measure momentum because
        changes in momentum precede changes in price.
      operationId: calculate_stoch
      parameters:
        - name: symbol
          in: query
          description: Ticker Symbol Required
          required: true
          style: form
          explode: true
          schema:
            type: string
        - name: period
          in: query
          description: The Analysis Period required
          required: true
          style: form
          explode: true
          schema:
            type: string
            enum:
              - day
              - hour
              - week
              - month
        - name: fast
          in: query
          description: The Fast %K period.
          required: false
          style: form
          explode: true
          schema:
            type: number
            default: 14
        - name: slow
          in: query
          description: The Slow %K period.
          required: false
          style: form
          explode: true
          schema:
            type: number
            default: 3
        - name: smooth_k
          in: query
          description: The Slow %D period.
          required: false
          style: form
          explode: true
          schema:
            type: number
            default: 3
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/stoch"
        "401":
          description: API key is missing or invalid
        "404":
          description: The specified symbol was not found
        "405":
          description: Validation exception
      x-openapi-router-controller: swagger_server.controllers.oscillators_controller
components:
  schemas:
    candlestick:
      type: object
      properties:
        timestamp:
          type: array
          items:
            type: string
            format: Date
            example: "1707436800000"
        Close:
          type: array
          items:
            type: number
        Open:
          type: array
          items:
            type: number
        High:
          type: array
          items:
            type: number
        Low:
          type: array
          items:
            type: number
        Volume:
          type: array
          items:
            type: number
        AdjClose:
          type: array
          items:
            type: number
      example:
        Close:
          - 0.8
          - 0.8
        Open:
          - 0.8
          - 0.8
        High:
          - 0.8
          - 0.8
        Low:
          - 0.8
          - 0.8
        Volume:
          - 0.8
          - 0.8
        AdjClose:
          - 0.8
          - 0.8
        timestamp:
          - "1707436800000"
    sma:
      type: object
      properties:
        timestamp:
          type: array
          items:
            type: string
            format: Date
            example: "1707436800000"
        Close:
          type: array
          items:
            type: number
        SMA:
          type: array
          items:
            type: number
      example:
        SMA:
          - 6.027
          - 6.027
        Close:
          - 0.8
          - 0.8
        Date:
          - "1707436800000"
    ema:
      type: object
      properties:
        timestamp:
          type: array
          items:
            type: string
            format: Date
            example: "1707436800000"
        Close:
          type: array
          items:
            type: number
        EMA:
          type: array
          items:
            type: number
      example:
        EMA:
          - 6.027
          - 6.027
        Close:
          - 0.8
          - 0.8
        timestamp:
          - "1707436800000"
          - "1707436800001"
    bollingernew:
      type: object
      properties:
        timestamp:
          type: array
          items:
            type: string
            format: Date
            example: "1707436800000"
        BBL:
          type: array
          items:
            type: number
        BBM:
          type: array
          items:
            type: number
        BBU:
          type: array
          items:
            type: number
        Close:
          type: array
          items:
            type: number
      example:
        BBU:
          - 1.46
          - 1.46
        Close:
          - 5.96
          - 5.96
        BBM:
          - 6.027
          - 6.02
        BBL:
          - 0.8
          - 0.8
        timestamp:
          - "1707436800000"
          - "1707436800001"
    psar:
      type: array
      items:
        $ref: "#/components/schemas/psar_inner"
    adx:
      type: array
      items:
        $ref: "#/components/schemas/adx_inner"
    cci:
      type: array
      items:
        $ref: "#/components/schemas/cci_inner"
    cmf:
      type: array
      items:
        $ref: "#/components/schemas/cmf_inner"
    roc:
      type: array
      items:
        $ref: "#/components/schemas/roc_inner"
    efi:
      type: array
      items:
        $ref: "#/components/schemas/efi_inner"
    mfi:
      type: array
      items:
        $ref: "#/components/schemas/mfi_inner"
    obv:
      type: array
      items:
        $ref: "#/components/schemas/obv_inner"
    adl:
      type: array
      items:
        $ref: "#/components/schemas/adl_inner"
    ppo:
      type: array
      items:
        $ref: "#/components/schemas/ppo_inner"
    pvo:
      type: array
      items:
        $ref: "#/components/schemas/pvo_inner"
    macd:
      type: array
      items:
        $ref: "#/components/schemas/macd_inner"
    rsi:
      type: array
      items:
        $ref: "#/components/schemas/rsi_inner"
    stoch:
      type: array
      items:
        $ref: "#/components/schemas/stoch_inner"
    psar_inner:
      type: object
      properties:
        timestamp:
          type: string
          format: timestamp
          example: "1707436800000"
        PSARl:
          type: number
          example: 145.02
        PSARs:
          type: number
          example: 154.02
        PSARaf:
          type: number
          example: 0.1
        PSARr:
          type: integer
          example: 1
      example:
        PSARr: 1
        PSARs: 154.02
        PSARl: 145.02
        PSARaf: 0.1
        timestamp: 1707436800000
    adx_inner:
      type: object
      properties:
        timestamp:
          type: string
          format: timestamp
          example: "1707436800000"
        ADX:
          type: number
          example: 145.02
        DMP:
          type: number
          example: 154.02
        DMN:
          type: number
          example: 0.1
      example:
        ADX: 1
        DMX: 154.02
        DMN: 145.02
        timestamp: 1707436800000
    macd_inner:
      type: object
      properties:
        timestamp:
          type: string
          format: timestamp
          example: "1707436800000"
        MACD:
          type: number
          example: 145.02
        MACDh:
          type: number
          example: 154.02
        MACDs:
          type: number
          example: 0.1
      example:
        MACD: 1
        HIST: 154.02
        SIG: 145.02
        timestamp: 1707436800000
    ppo_inner:
      type: object
      properties:
        timestamp:
          type: string
          format: timestamp
          example: "1707436800000"
        PPO:
          type: number
          example: 145.02
        HIST:
          type: number
          example: 154.02
        SIG:
          type: number
          example: 0.1
      example:
        PPO: 1
        HIST: 154.02
        SIG: 145.02
        timestamp: 1707436800000
    pvo_inner:
      type: object
      properties:
        timestamp:
          type: string
          format: timestamp
          example: "1707436800000"
        PVO:
          type: number
          example: 145.02
        HIST:
          type: number
          example: 154.02
        SIG:
          type: number
          example: 0.1
      example:
        PVO: 1
        HIST: 154.02
        SIG: 145.02
        timestamp: 1707436800000
    stoch_inner:
      type: object
      properties:
        timestamp:
          type: string
          format: timestamp
          example: "1707436800000"
        STOCHk:
          type: number
          example: 145.02
        STOCHd:
          type: number
          example: 154.02
      example:
        STOCHk: 1
        STOCHd: 154.02
        timestamp: 1707436800000
    cci_inner:
      type: object
      properties:
        timestamp:
          type: string
          format: timestamp
          example: "1707436800000"
        cci:
          type: number
          example: 145.02
      example:
        cci: 145.02
        timestamp: 1707436800000
    cmf_inner:
      type: object
      properties:
        timestamp:
          type: string
          format: timestamp
          example: "1707436800000"
        cmf:
          type: number
          example: 145.02
      example:
        cmf: 145.02
        timestamp: 1707436800000
    roc_inner:
      type: object
      properties:
        timestamp:
          type: string
          format: timestamp
          example: "1707436800000"
        roc:
          type: number
          example: 145.02
      example:
        roc: 145.02
        timestamp: 1707436800000
    efi_inner:
      type: object
      properties:
        timestamp:
          type: string
          format: timestamp
          example: "1707436800000"
        efi:
          type: number
          example: 145.02
      example:
        efi: 145.02
        timestamp: 1707436800000
    mfi_inner:
      type: object
      properties:
        timestamp:
          type: string
          format: timestamp
          example: "1707436800000"
        mfi:
          type: number
          example: 145.02
      example:
        mfi: 145.02
        timestamp: 1707436800000
    obv_inner:
      type: object
      properties:
        timestamp:
          type: string
          format: timestamp
          example: "1707436800000"
        obv:
          type: number
          example: 145.02
      example:
        obv: 145.02
        timestamp: 1707436800000
    adl_inner:
      type: object
      properties:
        timestamp:
          type: string
          format: timestamp
          example: "1707436800000"
        adl:
          type: number
          example: 145.02
      example:
        adl: 145.02
        timestamp: 1707436800000
    rsi_inner:
      type: object
      properties:
        timestamp:
          type: string
          format: timestamp
          example: "1707436800000"
        rsi:
          type: number
          example: 145.02
      example:
        rsi: 145.02
        timestamp: 1707436800000
  responses:
    UnauthorizedError:
      description: API key is missing or invalid
    NotFound:
      description: The specified symbol was not found
  parameters:
    symbol:
      name: symbol
      in: query
      description: Ticker Symbol Required
      required: true
      style: form
      explode: true
      schema:
        type: string
    start_date:
      name: start_date
      in: query
      description: Start Date of Analysis in YYYY-MM-DD Format
      required: true
      style: form
      explode: true
      schema:
        pattern: "^([0-9]{4})-(1[0-2]|0[1-9])-(3[01]|[12][0-9]|0[1-9])$"
        type: string
        format: Date
        example: 2019-05-17T00:00:00.000Z
    end_date:
      name: end_date
      in: query
      description: End Date of Analysis in YYYY-MM-DD Format
      required: true
      style: form
      explode: true
      schema:
        pattern: "^([0-9]{4})-(1[0-2]|0[1-9])-(3[01]|[12][0-9]|0[1-9])$"
        type: string
        format: Date
        example: 2019-05-17T00:00:00.000Z
    period:
      name: period
      in: query
      description: The Analysis Period in Days from Start Date
      required: true
      style: form
      explode: true
      schema:
        minimum: 1
        type: integer
    length_default_5:
      name: length
      in: query
      description: The short period
      required: false
      style: form
      explode: true
      schema:
        type: integer
        default: 5
    standard_deviation:
      name: standard_deviation
      in: query
      description: The long period
      required: false
      style: form
      explode: true
      schema:
        type: integer
        default: 2
    initial_acceleration:
      name: initial_acceleration
      in: query
      description: The psar initial acceleration
      required: false
      style: form
      explode: true
      schema:
        type: number
        default: 0.02
    acceleration:
      name: acceleration
      in: query
      description: The psar acceleration
      required: false
      style: form
      explode: true
      schema:
        type: number
        default: 0.02
    max_acceleration:
      name: max_acceleration
      in: query
      description: The psar max acceleration
      required: false
      style: form
      explode: true
      schema:
        type: number
        default: 0.2
    cci_scaling_constant:
      name: cci_scaling_constant
      in: query
      description: scaling constant
      required: false
      style: form
      explode: true
      schema:
        type: number
        default: 0.015
    length_default_14:
      name: length
      in: query
      description: period length
      required: false
      style: form
      explode: true
      schema:
        type: number
        default: 14
    length_default_20:
      name: length
      in: query
      description: period length
      required: false
      style: form
      explode: true
      schema:
        type: number
        default: 20
    length_default_13:
      name: length
      in: query
      description: period length
      required: false
      style: form
      explode: true
      schema:
        type: number
        default: 13
    length_default_1:
      name: length
      in: query
      description: period length
      required: false
      style: form
      explode: true
      schema:
        type: number
        default: 1
    drift:
      name: drift
      in: query
      description: diff period
      required: false
      style: form
      explode: true
      schema:
        type: number
        default: 1
    scalar:
      name: scalar
      in: query
      description: How much to magnify
      required: false
      style: form
      explode: true
      schema:
        type: number
        default: 100
    lensig:
      name: lensig
      in: query
      description: Signal Length
      required: false
      style: form
      explode: true
      schema:
        type: number
        default: 14
    fast:
      name: fast
      in: query
      description: The short period
      required: false
      style: form
      explode: true
      schema:
        type: number
        default: 12
    slow:
      name: slow
      in: query
      description: The long period
      required: false
      style: form
      explode: true
      schema:
        type: number
        default: 26
    signal:
      name: signal
      in: query
      description: The signal period
      required: false
      style: form
      explode: true
      schema:
        type: number
        default: 9
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      name: X-API-KEY
      in: header
      x-apikeyInfoFunc: swagger_server.controllers.authorization_controller.check_ApiKeyAuth
